name: Check PR with clang-format

on:
  push:
    branches:
      - 'rc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !github.event.deleted }}

    steps:
      - name: Compute branch names
        id: names
        env: 
          rc_branch: ${{ github.event.ref }}
        run: |
          echo "::set-output name=rc::${rc_branch#refs/heads/}"
          echo "::set-output name=base::${rc_branch#refs/heads/rc/}"

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.names.outputs.rc }}

      - name: Send pull request to regular branch
        uses: repo-sync/pull-request@v2.5
        with:
          destination_branch: ${{ steps.names.outputs.base }}
          github_token: ${{ secrets.ALIBUILD_GITHUB_TOKEN }}
          pr_title: 'daily tags: auto-update dist definitions'
          pr_body: |
            The daily-tags.sh script has created a tag release with these changes.
