name: Check PR with clang-format

on:
  push:
    branches:
      - 'rc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !github.event.deleted }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}

      - name: Compute base branch name
        id: name
        run: |
          echo "::set-output name=base::${GITHUB_REF#refs/heads/rc/}"

      - name: Debug
        run: |
          set -x
          echo source branch: $GITHUB_REF
          echo dest branch: ${{ steps.name.outputs.base }}

      - name: Send pull request to regular branch
        uses: repo-sync/pull-request@v2.5
        with:
          destination_branch: ${{ steps.name.outputs.base }}
          github_token: ${{ secrets.ALIBUILD_GITHUB_TOKEN }}
          pr_allow_empty: true
          pr_title: 'daily tags: auto-update dist definitions'
          pr_body: |
            The daily-tags.sh script has created a tag release with these changes.
