name: Check PR with clang-format

on:
  push:
    branches:
      - 'rc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !github.event.deleted }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compute base branch
        id: base
        env: 
          rc_branch: ${{ github.event.ref }}
        run: |
          echo "::set-output name=base::${rc_branch#refs/heads/rc/}"

      - name: Send pull request to regular branch
        uses: alisw/pull-request@master
        with:
          source_branch: ${{ github.event.ref }}
          destination_branch: ${{ steps.base.outputs.base }}
          github_token: ${{ secrets.ALIBUILD_GITHUB_TOKEN }}
          pr_title: 'daily tags: auto-update dist definitions'
          pr_body: |
            The daily-tags.sh script has created a tag release with these changes.
