name: Check PR with clang-format

on:
  push:
    branches:
      - 'rc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !github.event.push.deleted }}

    steps:
      - name: Get rc branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.ref }}

      - name: Compute base branch
        id: base
        env: 
          rc_branch: ${{ github.event.push.ref }}
        run: |
          set -x
          echo '${{ github.event }}'
          echo "rc_branch is $rc_branch" >&2
          echo "base is ${rc_branch#refs/heads/rc/}" >&2
          echo "::set-output name=base::${rc_branch#refs/heads/rc/}"

      - name: Send pull request to regular branch
        uses: alisw/pull-request@master
        with:
          source_branch: ${{ github.event.push.ref }}
          destination_branch: ${{ steps.base.outputs.base }}
          github_token: ${{ secrets.ALIBUILD_GITHUB_TOKEN }}
          pr_title: 'daily tags: auto-update dist definitions'
          pr_body: |
            The daily-tags.sh script has created a tag release with these changes.
